
spring:
  application:
    name: student-service

  datasource:
    url: ${secrets.db.url}
    username: ${secrets.db.username}
    password: ${secrets.db.password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${secrets.db.username}
    password: ${secrets.db.password}

  kafka:
    consumer:
      group-id: student-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: org.studentservice.model.CustomMessage
        spring.json.trusted.packages: "*"
    bootstrap-servers: localhost:9092

  config:
    import: "classpath:secrets.yml"


server:
  port: 8092
